name: mogely
favicon: null
layout_spectrum: 0.8909122841432691
typography_spectrum: 0.5098067524377257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7533117474522442
  lightness: 0.39691759110428393
  saturation: 0.9760920049156994
  rhythmicContrast: 0.193688198691234
purpose: []
